### PR TITLE
intro to pandas slides

### LINKED ISSUE #19: Slides: Intro to Pandas
Sources:

Currently, the slides on pandas are somewhat spread out. Intro material for pandas can be drawn from:

* Intro class:
  * [Selecting and Filtering](https://github.com/uc-python/intro-python-datasci/blob/master/notebooks/05-Selecting-and-Filtering.ipynb)
  * [Manipulating and Creating Columns](https://github.com/uc-python/intro-python-datasci/blob/master/notebooks/06-Manipulating-Columns.ipynb)
  * [Summarizing Data](https://github.com/uc-python/intro-python-datasci/blob/master/notebooks/08-Summarizing-Data.ipynb)
* BANA 6043:
  * [Lesson 2c](https://github.com/bradleyboehmke/uc-bana-6043/blob/main/book/02-module/lesson-2c.ipynb)
  * [Lesson 3a](https://github.com/bradleyboehmke/uc-bana-6043/blob/main/book/03-module/lesson-3a.ipynb)
  * [Lesson 3b](https://github.com/bradleyboehmke/uc-bana-6043/blob/main/book/03-module/lesson-3b.ipynb)
  * [Lesson 3c](https://github.com/bradleyboehmke/uc-bana-6043/blob/main/book/03-module/lesson-3c.ipynb)

### PR DESCRIPTION
**Pull request by cunningjames**
Closes #19.

had a bit of trouble deciding how to handle this one. There's a lot of content to cover for an hour fifteen.

Using the BANA-6043 book's notebooks as a starting point, I cut out a bunch of material and extrapolated where I thought necessary. Let me know if you think I should cut out any more, but I think what I've covered here is pretty minimal for an intro to pandas session. 

Possibly aggregations could be moved to advanced, but I'm iffy about that one.

### CODE REVIEW

**Review by augustopher — COMMENTED** [review]
GitHub won't let me view/comment on the notebook diff, so here's a big list of them:

- Line 302: Given the width and context of this comment, I would move it out of the code block and prefix with "**Note:**"
- Line 708: This code block is cutting off. It's only the `']]` bit, but these don't scroll in the slides (unlike the data frame outputs)
- Line 1578: Same as 708 - just a few characters cut at the end
- Line 2183: Same as 708, but missing the last column re-name and `.head()`
- Line 3473: Same as 2183 - cutting off about half the code
- Lines 4071-4072: ends of the comments are getting cut off - either move them above corresponding line, or shorten
- Line 4850: Last half of the code is cut off
- Line 5715: Last bit of code cut off
- Line 5982: same as 5715
- Line 6119: same as 5715
- Should have the same wrap-up "Questions" slide at the end

**Comment by cunningjames** [comment]
@augustopher, I believe I've addressed all of your comments now.

**Review by augustopher — APPROVED** [review]

**Review by eswan18 — CHANGES_REQUESTED** [review]
Only one tiny thing: "luxery" on the slide "Applying custom functions"

A note, but nothing to change, is that a fair number of these slides either use something like `.head()` – which we explain but does add noise to the main point of the slide – or a new feature/syntax (e.g. wrapping line breaks using parentheses) – which will distract students a little. I think it's okay to mix multiple concepts but it does mean that we need to slow down and maybe even live code a little.

**Comment by cunningjames** [comment]
I thought I got all the "luxery"s out of there ... blame Brad for that one. ;)

Originally the slides did not use `.head()` so heavily, nor did they wrap expressions in parentheses. But it was difficult fitting everything on a slide otherwise. I haven't looked at the earlier slide decks in detail yet, so I just assumed the parentheses-wrapping would have come up at some point. Regardless, I think we can explain that pretty quickly.

**Review by augustopher — APPROVED** [review]

**Comment by bradleyboehmke** [comment]
> I thought I got all the "luxery"s out of there ... blame Brad for that one. ;)
> 
> Originally the slides did not use `.head()` so heavily, nor did they wrap expressions in parentheses. But it was difficult fitting everything on a slide otherwise. I haven't looked at the earlier slide decks in detail yet, so I just assumed the parentheses-wrapping would have come up at some point. Regardless, I think we can explain that pretty quickly.

Throughing me undr the buz for bed speling!!!  I nevr clamed to be guud at it ;)

**Comment by cunningjames** [comment]
Brad's editor whenever he submits a new book draft ... https://cards.scryfall.io/large/front/4/c/4c08bd24-5710-4548-8966-9c5e81744680.jpg?1562488379

**Pull request merged**
